http://localhost:3001/
Content-Type: application/json

###

POST http://localhost:3001/newUser
Content-Type: application/json

{
    "fName": "Jonathan",
    "sName": "Mwaniki",
     "email": "jonatskin3@gmail.com",  
    "password": "Bjjdjdjka1$",
    "cPassword": "Bjjdjdjka1$"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "jonatskin@gmail.com",  
    "password": "Bjjdjdjka1$"
}